# Generated by Django 5.0.2 on 2024-02-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortenedurl",
            name="original_url",
            field=models.URLField(max_length=700),
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="shortened_url",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
