# Generated by Django 5.0.2 on 2024-02-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener_api", "0002_alter_shortenedurl_original_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shortenedurl",
            name="shortened_url",
        ),
        migrations.AddField(
            model_name="shortenedurl",
            name="shortened_url_key",
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
