# Generated by Django 5.0.2 on 2024-02-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener_api", "0003_remove_shortenedurl_shortened_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortenedurl",
            name="shortened_url_key",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
