# Generated by Django 5.0.2 on 2024-02-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener_api", "0004_alter_shortenedurl_shortened_url_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortenedurl",
            name="shortened_url_value",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="shortened_url_key",
            field=models.CharField(default="ism.ca/", max_length=10),
        ),
    ]
