# Generated by Django 5.0.2 on 2024-02-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener_api", "0006_remove_shortenedurl_shortened_url_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortenedurl",
            name="original_url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="shortened_url_value",
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
